LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

GLTUTORIAL_SRC := $(wildcard $(LOCAL_PATH)/*.c)
GLTUTORIAL_INCLUDES := $(wildcard $(LOCAL_PATH)/*.h)

LOCAL_MODULE := gltutorial

LOCAL_C_INCLUDES := $(GLTUTORIAL_INCLUDES:$(LOCAL_PATH)/%=%)
LOCAL_SRC_FILES := $(GLTUTORIAL_SRC:$(LOCAL_PATH)/%=%)

LOCAL_CFLAGS := -std=c99
LOCAL_LDLIBS := -lGLESv1_CM -llog

include $(BUILD_SHARED_LIBRARY)